<?xml version="1.0" encoding="UTF-8"?>
<DocumentRoot xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="http://www.intervoice.com/schema/message/1.0">
  <messageEditor>
    <audio>
      <application>
        <messages>
          <message id="m1" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="welcome to the international bank automated service line."/>
          </message>
          <message id="m2" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="i can provide you with your current and available balances, play your last 6 checks, or convert american dollars into foreign currency."/>
          </message>
          <message id="m3" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="but, before i can continue i'll need your 5 digit account number."/>
          </message>
          <message id="m4" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="please hold while i access your account."/>
          </message>
          <message id="m5" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="main menu"/>
          </message>
          <message id="m6" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="so what would you like to do? get balances, hear you last 6 checks, or convert currency."/>
          </message>
          <message id="m103" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="i'm sorry i'm having trouble with my computer."/>
          </message>
          <message id="m100" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="i'm sorry i didn't catch that. please say or enter your 5 digit account number."/>
          </message>
          <message id="m101" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="i'm sorry i didn't hear that. please say or enter your 5 digit account number."/>
          </message>
          <message id="m102" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="please say get balances, hear my last 6 checks, or convert currency."/>
          </message>
          <message id="m104" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="sorry, my records show no data for this account number."/>
          </message>
          <message id="m20" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="please call back later. goodbye."/>
          </message>
          <message id="m7" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="check number"/>
          </message>
          <message id="m8" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="in the amount of"/>
          </message>
          <message id="m9" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="was paid on "/>
          </message>
          <message id="m10" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="that's all i have."/>
          </message>
          <message id="m11" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="well, if you're done just hang up otherwise i'll take you back to the main menu."/>
          </message>
          <message id="m12" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="okay, your current balance is "/>
          </message>
          <message id="m13" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="and your available balance is"/>
          </message>
          <message id="m14" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="sorry we're closed. "/>
          </message>
          <message id="m15" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="please hold while i transfer you to a representative."/>
          </message>
          <message id="m16" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="currency conversion"/>
          </message>
          <message id="m17" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="i can convert american dollars to pesos, pounds, canadian or euro dollars."/>
          </message>
          <message id="m18" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="so which one would you like?"/>
          </message>
          <message id="m105" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="please say which currency you want your dollars converted to, pesos, pounds, canadian, or euros"/>
          </message>
          <message id="m19" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="and how much would you like to convert?"/>
          </message>
          <message id="m106" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="before i can convert your money, i will need to know how much you want to convert."/>
          </message>
          <message id="m21" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="okay, currently"/>
          </message>
          <message id="m22" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="converts to "/>
          </message>
          <message id="m23" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="pkease hold while i calculate it."/>
          </message>
          <message id="m24" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="i'm still calculating it."/>
          </message>
          <message id="m25" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="canadian aye"/>
          </message>
          <message id="m26" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="pesos"/>
          </message>
          <message id="m27" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="euros"/>
          </message>
          <message id="m28" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="pounds"/>
          </message>
          <message id="m107" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="sorry i'm having problems with my calculator."/>
          </message>
          <message id="m108" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="sorry i just can't seem to hear you."/>
          </message>
          <message id="m109" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="sorry i just can't understand you."/>
          </message>
        </messages>
        <messageGroups>
          <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
        </messageGroups>
      </application>
    </audio>
  </messageEditor>
</DocumentRoot>
