<?xml version="1.0" encoding="UTF-8"?>
<DocumentRoot xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="http://www.intervoice.com/schema/message/1.0">
  <messageEditor>
    <audio>
      <application>
        <messages>
          <message id="m7" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="check number"/>
          </message>
          <message id="m8" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="in the amount of"/>
          </message>
          <message id="m9" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="was paid on"/>
          </message>
          <message id="m10" type="wav">
            <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
            <messageText country="United States" language="English" speaker="default" text="that's all i have"/>
          </message>
        </messages>
        <messageGroups>
          <messageGroup name="default" description="This is the default group with which all messages are intially associated."/>
        </messageGroups>
      </application>
    </audio>
  </messageEditor>
</DocumentRoot>
