<?xml version="1.0" encoding="UTF-8"?>
<DocumentRoot xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns="http://www.intervoice.com/schema/message/1.0">
  <messageEditor>
    <audio>
      <application>
        <messages/>
        <messageGroups>
          <messageGroup name="default" description="This is the default group with which all messages are initially associated."/>
        </messageGroups>
      </application>
    </audio>
  </messageEditor>
</DocumentRoot>
